name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Format, check, and test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup default stable

      - name: Check formatting
        run: cargo fmt --check

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test
